version: '3'

services:
  app-robyn:
    container_name: stac-api-robyn
    image: jonhealy1/stac-api-robyn
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      - RELOAD=true
      - MONGO_USER=dev
      - MONGO_PASS=stac
      - MONGO_PORT=27017
      - MONGO_HOST=172.17.0.1
    ports:
      - "5000:5000"
    volumes:
      - ./stac_api_robyn:/app/stac_api_robyn
      - ./scripts:/app/scripts
    depends_on:
      - mongo_db
    command:
      bash -c "./scripts/wait-for-it.sh mongo_db:27017 && python -m stac_api_robyn.app"

  mongo_db:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "dev"
      MONGO_INITDB_ROOT_PASSWORD: "stac"
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"
    command: mongod

networks:
  default:
    name: stac-api-robyn
